
import { Montserrat, Roboto } from "next/font/google"; 
import "./globals.css";

// Configure as fontes
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: '--font-montserrat', 
  weight: ['700', '900']
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: '--font-roboto',
  weight: ['400', '500']
});

export const metadata = {
  title: "ECOS - Great Things Are Coming",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Aplique as variáveis da fonte ao body */}
      <body className={`${montserrat.variable} ${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}